management:
  endpoint:
    health:
      show-details: when_authorized

## Server Properties
server:
  port: 8080
  servlet:
    context-path: /api/garbus

spring:
  banner:
    location: ./banner.txt
  application:
    name: GARBUS

  #Java Persistence API
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
#          ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: 'PUBLIC'

  # DB Connection Configuration
  datasource:
    initialization-mode: embedded
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PSW}
    driverClassName: org.postgresql.Driver