management:
  endpoint:
    health:
      show-details: when_authorized

spring:
  application:
    name: 'GARBUS'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: 'PUBLIC'
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    initialization-mode: always
    url: ${DB_URL}
    username: ${DB_USR}
    password: ${DB_PSW}
    driverClassName: org.h2.Driver