SELECT * FROM dual;


DROP TABLE IF EXISTS PREDIOS;
DROP TABLE IF EXISTS LIXEIRAS;
DROP TABLE IF EXISTS LIXEIRA_EVENTOS;
DROP TABLE IF EXISTS EVENTOS;
DROP TABLE IF EXISTS ZONAS;
DROP TABLE IF EXISTS LIXEIRA_STATUS;
DROP TABLE IF EXISTS TIPO_LIXEIRA;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS PERFIS;
DROP TABLE IF EXISTS USUARIO_ZONA;

/* brModelo: */

CREATE TABLE EVENTOS (
                         ID INTEGER PRIMARY KEY,
                         TIPO VARCHAR NOT NULL,
                         DESCRICAO VARCHAR NOT NULL,
                         DATA TIMESTAMP NOT NULL
);

/* brModelo: */

CREATE TABLE ZONAS (
                       ID INTEGER PRIMARY KEY,
                       NOME VARCHAR NOT NULL NOT NULL,
                       DESCRICAO VARCHAR NOT NULL,
                       LOCAL VARCHAR NOT NULL
);

/* brModelo: */

CREATE TABLE LIXEIRA_STATUS (
                                ID INTEGER PRIMARY KEY,
                                NOME VARCHAR NOT NULL,
                                DESCRICAO VARCHAR NOT NULL
);

/* brModelo: */

CREATE TABLE TIPO_LIXEIRA (
                              ID INTEGER PRIMARY KEY,
                              NOME VARCHAR NOT NULL,
                              DESCRICAO VARCHAR NOT NULL
);

/* brModelo: */

CREATE TABLE PERFIS (
                        ID INTEGER PRIMARY KEY,
                        NOME VARCHAR NOT NULL,
                        DESCRICAO VARCHAR NOT NULL
);

/* brModelo: */

CREATE TABLE PREDIOS (
                         ID INTEGER PRIMARY KEY,
                         NOME VARCHAR NOT NULL,
                         ID_ZONA INTEGER NOT NULL
);

ALTER TABLE PREDIOS ADD CONSTRAINT FK_PREDIOS_ZONAS
    FOREIGN KEY (ID_ZONA)
        REFERENCES ZONAS (ID);

/* brModelo: */

CREATE TABLE USUARIOS (
                          ID INTEGER PRIMARY KEY,
                          EMAIL VARCHAR,
                          NOME VARCHAR NOT NULL,
                          LOGIN VARCHAR NOT NULL,
                          SENHA VARCHAR NOT NULL,
                          BLOQUEADO BOOLEAN NOT NULL DEFAULT FALSE,
                          DT_CADASTRO TIMESTAMP NOT NULL,
                          ID_PERFIL INTEGER
);

ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_PERFIS
    FOREIGN KEY (ID_PERFIL)
        REFERENCES PERFIS (ID);

/* brModelo: */

CREATE TABLE USUARIO_ZONA (
                              ID INTEGER PRIMARY KEY,
                              ID_USUARIO INTEGER,
                              ID_ZONA INTEGER
);

ALTER TABLE USUARIO_ZONA ADD CONSTRAINT FK_USUARIO_ZONA
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS (ID);

ALTER TABLE USUARIO_ZONA ADD CONSTRAINT FK_ZONA_USUARIO
    FOREIGN KEY (ID_ZONA)
        REFERENCES USUARIOS (ID);

/* brModelo: */

CREATE TABLE LIXEIRAS (
                          ID INTEGER PRIMARY KEY,
                          MARCA VARCHAR NOT NULL,
                          DESCRICAO VARCHAR NOT NULL,
                          CAPACIDADE DOUBLE NOT NULL,
                          OCUPACAO DOUBLE NOT NULL,
                          EXCLUIDO BOOLEAN NOT NULL DEFAULT FALSE,
                          ID_STATUS INTEGER,
                          ID_TIPO INTEGER,
                          ID_PREDIO INTEGER,
                          ID_ZONA INTEGER
);

ALTER TABLE LIXEIRAS ADD CONSTRAINT FK_LIXEIRAS_PREDIOS
    FOREIGN KEY (ID_PREDIO)
        REFERENCES PREDIOS (ID);

ALTER TABLE LIXEIRAS ADD CONSTRAINT FK_TIPO_LIV
    FOREIGN KEY (ID_TIPO)
        REFERENCES TIPO_LIXEIRA (ID);

ALTER TABLE LIXEIRAS ADD CONSTRAINT FK_LIXEIRA_STATUS
    FOREIGN KEY (ID_STATUS)
        REFERENCES LIXEIRA_STATUS (ID);

ALTER TABLE LIXEIRAS ADD CONSTRAINT FK_ZONAS_LIXEIRAS
    FOREIGN KEY (ID_ZONA)
        REFERENCES ZONAS (ID);

ALTER TABLE LIXEIRAS ADD CONSTRAINT LIXEIRA_PREDIO_OR_ZONA
    CHECK (ID_ZONA IS NULL OR ID_PREDIO IS NULL);

/* brModelo: */

CREATE TABLE LIXEIRA_EVENTOS (
                                 ID INTEGER PRIMARY KEY,
                                 ID_EVENTO INTEGER,
                                 ID_LIXEIRA INTEGER,
                                 ID_USUARIO INTEGER,
                                 DATA TIMESTAMP NOT NULL
);

ALTER TABLE LIXEIRA_EVENTOS ADD CONSTRAINT FK_LIXEIRA_EVENTOS_EVENTOS
    FOREIGN KEY (ID_EVENTO)
        REFERENCES EVENTOS (ID);

ALTER TABLE LIXEIRA_EVENTOS ADD CONSTRAINT FK_LIXEIRA_EVENTOS_USUARIOS
    FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS (ID);

ALTER TABLE LIXEIRA_EVENTOS ADD CONSTRAINT FK_LIXEIRA_EVENTOS_LIXEIRA
    FOREIGN KEY (ID_LIXEIRA)
        REFERENCES LIXEIRAS (ID);