version: "2"

services:
  sonarqube:
    image: "sonarqube:7.9-community"
    ports:
      - "9988:9000"
    networks:
      - sonarnet
    depends_on:
      - db
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
      #- /data/docker/sonarqube/conf:/opt/sonarqube/conf
      - /data/docker/sonarqube/data:/opt/sonarqube/data
      - /data/docker/sonarqube/logs:/opt/sonarqube/logs
      - /data/docker/sonarqube/extensions:/opt/sonarqube/extensions

  db:
    image: postgres:9.6.14
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /data/docker/sonarqube/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - /data/docker/sonarqube/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
